#!/usr/bin/env python

# http://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory

import sys

with open(sys.argv[1], 'rb+') as f:
    content = f.read()
    f.seek(0)
    f.write(content.replace(b'\r', b''))
    f.truncate()
