
# 2025Mar24
# super0-simple makefile to construct a sample program based on content
# of page 14 of "Understanding and Using C Pointers", Richard Reese

all: pg14 type_sizes

clean:
	rm -f *.o pg14 type_sizes

